<?php

namespace AppBundle\Repository;

/**
 * PesertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PesertaRepository extends \Doctrine\ORM\EntityRepository
{
}
