security:
 encoders:
  Symfony\Component\Security\Core\User\user: plaintext
  
 providers:
  in_memory:
   memory:
    users:
     admin:
      password: 'suneo'
      roles:
       - ROLE_USER
 firewalls:
  dev:
   pattern: ^/(_(profiler|wdt)|css|images|js)/
   security: false
   
  default:
   anonymous: ~
   http_basic: ~
   stateless: true
   
 access_control:
  - { path: /.*, roles: ROLE_USER }
